name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t shadowfax-flask-app .
        
      - name: Push Docker image
        run: |
          docker tag shadowfax-flask-app ${{ secrets.DOCKER_USERNAME }}/shadowfax-flask-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/shadowfax-flask-app:latest
     
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/shadowfax-flask-app:latest
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d -p 5000:5000 --name flask-app ${{ secrets.DOCKER_USERNAME }}/shadowfax-flask-app:latest
